#### Numpy

In [1]:
!pip install numpy

In [ ]:
import numpy as np

# Create arrays using numpy
# Create a 1D Array 

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr1 = np.array([1,2,3,4,5,6])
arr1.reshape((2,3)) # 2 Rows and 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# 2D Array

arr2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr2)
print()
print(arr2.shape)
print()
print(arr2.reshape((3,4)))
print()
print(arr2.reshape((4,3)))
print()

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

(2, 6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]



In [20]:
print(np.arange(0,10,2).reshape(1,5))
print()
print(np.arange(0,10,2).reshape(5,1))

[[0 2 4 6 8]]

[[0]
 [2]
 [4]
 [6]
 [8]]


In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
# Identity matrix

print(np.eye(4))
print()
print(np.eye(3))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# attributes of Numpy Array

arr = np.array([[1,2,3],[4,5,6]])

print("Array: \n", arr)
print("Shape: ", arr.shape)
print("Number of dimentions: ",arr.ndim)
print("size (number of elements): ",arr.size)
print("Data type: ", arr.dtype)
print("Item size (in bytes): ", arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimentions:  2
size (number of elements):  6
Data type:  int64
Item size (in bytes):  8


In [27]:
# Numpy Vectorization Operation 

arr3 = np.array([1,2,3,4,5,6])
arr4 = np.array([10,20,30,40,50,60])

# Element wise Addition

print("Addition: ", arr3 + arr4)

# Element wise substraction

print("Substraction: ", arr3, arr4)

# Element  wise multiplication

print("Multiplication: ", arr3 * arr4)

# Element wise division

print("Division: ", arr3 / arr4)

Addition:  [11 22 33 44 55 66]
Substraction:  [1 2 3 4 5 6] [10 20 30 40 50 60]
Multiplication:  [ 10  40  90 160 250 360]
Division:  [0.1 0.1 0.1 0.1 0.1 0.1]


In [28]:
# Universal Functions

arr = np.array([2,3,4,5,6])

# square root
print("Square root: ",np.sqrt(arr))

# Exponential
print("Exponential: ",np.exp(arr))

# Sine 
print("Sine: ",np.sin(arr))

# Natural log
print("NAtural log: ",np.log(arr))

Square root:  [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential:  [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sine:  [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
NAtural log:  [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [29]:
# Array Slicing and Indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [31]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [32]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [33]:
# Modify array elements

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [34]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [37]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5, 6, 5, 6])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)



Normalized data: [-1.73205081 -1.15470054 -0.57735027  0.          0.57735027  1.15470054
  0.57735027  1.15470054]


In [38]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])